# Generated by Django 5.2.6 on 2025-09-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='СashFlow',
            new_name='CashFlow',
        ),
    ]
